import Head from 'next/head'
import Image from 'next/image'
import React, { BaseSyntheticEvent, ChangeEvent, ChangeEventHandler, MouseEvent, useState } from 'react'
import Switch from '../components/Checkbox/checkbox'
import Modal, { ModalFooterButton } from '../components/Modal/Modal'
import styles from '../styles/Home.module.css'
import Form, { FormButton, FormInput, FormTextArea } from '../X-components/Form'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {faVideo} from '@fortawesome/free-solid-svg-icons'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { KRMLogo } from '../components/KR/Logo'
import { DataHandler } from '../utils/DataHandler'
import { getSession, signIn, useSession } from "next-auth/react";
import { GetServerSideProps, NextPage } from 'next'

const AblyChatComponent = dynamic(() => import('../components/Ably/AblyChatComponent'), { ssr: false });

const Home : NextPage = () => {
	
	const session = useSession();

	const [test, setTest] = useState(false)

	const [modals, setModals] = useState({
		test1 : false,
		test2 : false,
	})

	const ModalOpenHandler = ({target : { name }} : BaseSyntheticEvent) => setModals(prev => ({...prev,[name] : true}))
	const ModalCloseHandler = ({target : { name }} : BaseSyntheticEvent) => setModals(prev => ({...prev,[name] : false}))

	const TestSubmit = (e : React.FormEvent) => {
		e.preventDefault();
		console.log("RESR",session)
	}

	const HandleLoginSubmit = async (e : React.FormEvent) => {
		e.preventDefault()
		const res = await signIn('credentials',{
				username : loginData.email,
				password : loginData.password,
				redirect : false
		})
		console.log("RES",res)
}

	type LoginDataType = {
		email : string,
		password : string,
	}

	const LoginDataHandler = (e : React.ChangeEvent<Element>) => { DataHandler<LoginDataType>(e,setLoginData) }

	const [loginData, setLoginData] = useState<LoginDataType>({
		email : "",
		password : "",
	})

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Switch setState={setTest} state={test}/>

			<main className={styles.main}>
				<Modal
				header={[<KRMLogo key={"krm_login_logo"}/>]}
				show={true} name={''} background={"#2d3436"}>
					<Form onSubmit={HandleLoginSubmit}>
							<FormInput name={'email'} m='0 0 1em 0'
								placeHolder={"sample@email.com"}
								onChange={LoginDataHandler}
								value={loginData.email}/>
							<FormInput name={'password'} m='0 0 1em 0'
								type={"password"}
								placeHolder={"password"}
								onChange={LoginDataHandler}
								value={loginData.password}/>
							<FormButton m='0 .1em' primary content={"Login"} type={"submit"}/>
							<FormButton m='0 .1em' primary content={"TEST"} onClick={TestSubmit}/>
					</Form>
				</Modal>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}

export default Home;